In [51]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde
from shapely.geometry import Point, Polygon
from scipy.spatial import ConvexHull

In [52]:
excel_file_path0 = 'C:/Users/weisz/OneDrive/Documents/中信兄弟/程式碼/Pitch Value/RE288.xlsx'
sheet_name = 'Sheet1'
RE = pd.read_excel(excel_file_path0, sheet_name=sheet_name)

In [53]:
df = pd.read_csv("C:/Users/weisz/Downloads/1.csv")

In [54]:
df

,LocalDateTime,away,home,id,gameId,stadium,umpireInChief,date,eType,awayScores,...,fielder_C,fielder_FB,fielder_SB,fielder_TB,fielder_SS,fielder_LF,fielder_CF,fielder_RF,fielder_DH,trackMan
0,'2026-05-09T17:05:36.0160+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,豊暐,高國麟,林澤彬,王念好,池恩齊,王苡丞,周佳樂,童堉誠,王勝偉,"{""PitchNo"":""1"",""Date"":""2026/5/9"",""Time"":""05:11..."
1,'2026-05-09T17:05:51.4260+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097c,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,豊暐,高國麟,林澤彬,王念好,池恩齊,王苡丞,周佳樂,童堉誠,王勝偉,"{""PitchNo"":""2"",""Date"":""2026/5/9"",""Time"":""05:26..."
2,'2026-05-09T17:06:10.7310+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097b,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,豊暐,高國麟,林澤彬,王念好,池恩齊,王苡丞,周佳樂,童堉誠,王勝偉,"{""PitchNo"":""3"",""Date"":""2026/5/9"",""Time"":""05:45..."
3,'2026-05-09T17:06:31.3200+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097a,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,豊暐,高國麟,林澤彬,王念好,池恩齊,王苡丞,周佳樂,童堉誠,王勝偉,"{""PitchNo"":""4"",""Date"":""2026/5/9"",""Time"":""06:06..."
4,'2026-05-09T17:06:50.7770+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0979,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,豊暐,高國麟,林澤彬,王念好,池恩齊,王苡丞,周佳樂,童堉誠,王勝偉,"{""PitchNo"":""5"",""Date"":""2026/5/9"",""Time"":""06:25..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,'2026-05-09T20:40:14.2510+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0825,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,林辰勳,石翔宇,李凱威,劉基鴻,張政禹,冉皓燐,郭天信,曾聖安,李展毅,"{""PitchNo"":""335"",""Date"":""2026/5/9"",""Time"":""39:..."
345,'2026-05-09T20:40:51.7830+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0824,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,林辰勳,石翔宇,李凱威,劉基鴻,張政禹,冉皓燐,郭天信,曾聖安,李展毅,"{""PitchNo"":""336"",""Date"":""2026/5/9"",""Time"":""40:..."
346,'2026-05-09T20:41:07.6830+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0823,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,林辰勳,石翔宇,李凱威,劉基鴻,張政禹,冉皓燐,郭天信,曾聖安,李展毅,"{""PitchNo"":""337"",""Date"":""2026/5/9"",""Time"":""40:..."
347,'2026-05-09T20:41:35.1270+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0822,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,林辰勳,石翔宇,李凱威,劉基鴻,張政禹,冉皓燐,郭天信,曾聖安,李展毅,"{""PitchNo"":""338"",""Date"":""2026/5/9"",""Time"":""41:..."
348,'2026-05-09T20:41:53.7400+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0821,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,林辰勳,石翔宇,李凱威,劉基鴻,張政禹,冉皓燐,郭天信,曾聖安,李展毅,"{""PitchNo"":""339"",""Date"":""2026/5/9"",""Time"":""41:..."

In [55]:
#col = ['LocalDateTime','GameID','umpireInChief','date','stadium','bHand','pHand','strikes','balls','outs','side','inning','coordX','coordY','pType','call','result','bName','bTeamId', 'pName','pTeamId', 'gameId', 'paRound', 'paOrder',"runsOnPlay",'firstId','secondId','thirdId']

In [56]:
name_mapping = {
    '65630ee55559b6d7a6d5d200':'兄弟',
    '65630ee95559b6d7a6d5d201':'味全', 
    '65630eed5559b6d7a6d5d202':'樂天', 
    '65630ef25559b6d7a6d5d203':'統一',
    '65630ef65559b6d7a6d5d204':'富邦',
    '6569a9ddaf62a48d3f94b422':'台鋼',
    }

# 新增一列"球員"，根据"Pitcher"列的值匹配中文名
df['進攻球隊'] = df['bTeamId'].map(name_mapping)

In [57]:
name_mapping = {
    '65630ee55559b6d7a6d5d200':'兄弟',
    '65630ee95559b6d7a6d5d201':'味全', 
    '65630eed5559b6d7a6d5d202':'樂天', 
    '65630ef25559b6d7a6d5d203':'統一',
    '65630ef65559b6d7a6d5d204':'富邦',
    '6569a9ddaf62a48d3f94b422':'台鋼',
    }

# 新增一列"球員"，根据"Pitcher"列的值匹配中文名
df['防守球隊'] = df['pTeamId'].map(name_mapping)

In [58]:
df.loc[:, 'Year'] = df['date'].str[:4]
#df.loc[:, 'Year'] = df['date'].astype(str).str[:4]
df.loc[:, '日期'] = df['date'].str[:10]

In [59]:
df = df[~df['result'].isin(['GO','2B', '1B', 'FO', 'SH', 'E', 'GIDP', 'FC','HBP', 'HR', '3B', 'IBB', 'SF', 'IGNORE', 'DP', 'D3S', 'ID', 'IH'])]
df = df[~df['call'].isin(['F', 'SW', 'CS', 'FT_MISS', 'FOUL_BUNT','FT','TRY_BUNT', 'H', 'BUNT'])]
df= df.dropna(subset=['call'])

In [60]:
name_mapping = {
    'FF':'直球', 
    'CH':'變速球', 
    'FC':'卡特球', 
    'CU':'曲球', 
    'FO':'指叉球',
    'SL':'滑球', 
    'SI':'伸卡球',
    'KN':'彈指曲球', 
    'EP':'小便球'
}

# 新增一列"球員"，根据"Pitcher"列的值匹配中文名
df['球種'] = df['pType'].map(name_mapping)

In [61]:
feild_items = df['stadium'].unique()
feild_items

array(['新北市立新莊棒球場'], dtype=object)

In [62]:
# 1. 定義好球帶邊界
STRIKE_ZONE_LEFT = -50
STRIKE_ZONE_RIGHT = 50
STRIKE_ZONE_BOTTOM = -50
STRIKE_ZONE_TOP = 50

def in_strike_zone(x, y):
    # 使用 <= 與 >= 已經完整包含了「碰到線也算」的邏輯
    return (STRIKE_ZONE_LEFT <= x <= STRIKE_ZONE_RIGHT) and \
           (STRIKE_ZONE_BOTTOM <= y <= STRIKE_ZONE_TOP)

# 2. 判斷是否為規則上的好球 (Rulebook Strike)
df["rulebook_strike"] = df.apply(lambda row: in_strike_zone(row["coordX"], row["coordY"]), axis=1)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 173 entries, 0 to 347
Columns: 276 entries, LocalDateTime to rulebook_strike
dtypes: bool(6), float64(139), int64(15), object(116)
memory usage: 367.3+ KB

In [64]:
RE

,Unnamed: 0,壘包狀態,壞球,好球,出局數,出現次數,總得分,Expected_Runs,比例,加權得分期望值
0,0,0,0,0,0,15553,9684,0.622645,0.045999,0.028641
1,1,0,0,0,1,10686,5897,0.551844,0.031604,0.017441
2,2,0,0,0,2,8220,4396,0.534793,0.024311,0.013001
3,4,0,0,1,0,9515,5892,0.619233,0.028141,0.017426
4,5,0,0,1,1,6461,3603,0.557654,0.019109,0.010656
...,...,...,...,...,...,...,...,...,...,...
283,294,7,3,1,1,114,169,1.482456,0.000337,0.000500
284,295,7,3,1,2,120,180,1.500000,0.000355,0.000532
285,296,7,3,2,0,93,145,1.559140,0.000275,0.000429
286,297,7,3,2,1,238,346,1.453782,0.000704,0.001023
287,298,7,3,2,2,271,320,1.180812,0.000801,0.000946

In [65]:
df["is_correct"] = df.apply(
    lambda row: (row["call"] == "S" and row["rulebook_strike"]) or 
                (row["call"] == "B" and not row["rulebook_strike"]),
    axis=1
)

accuracy_by_umpire = df.groupby("umpireInChief")["is_correct"].mean().reset_index()
accuracy_by_umpire.rename(columns={"is_correct":"accuracy"}, inplace=True)
accuracy_by_umpire['accuracy']=accuracy_by_umpire['accuracy']*100
accuracy_by_umpire

  umpireInChief   accuracy
0           江春緯  86.127168

## 裁判分數計算

In [66]:
df_ump = df.copy()

In [67]:
def base_state(row):
    state = 0
    if not pd.isna(row['firstId']):
        state += 1
    if not pd.isna(row['secondId']):
        state += 2
    if not pd.isna(row['thirdId']):
        state += 4
    return state

mask2 = df_ump['Year'].isin(['2023', '2024', '2025','2026'])
df_ump.loc[mask2, '壘包狀態編號'] = df_ump.loc[mask2].apply(base_state, axis=1)
df_ump.loc[mask2, '壘包狀態編號'] = df_ump.loc[mask2, '壘包狀態編號'].fillna(0)

df_ump['PitchCount'] = df_ump.groupby(['gameId', 'pName']).cumcount() + 1

In [68]:
name_mapping = {
    0:'無人在壘',
    1:'一壘有人', 
    2:'二壘有人',
    3:'一二壘有人',
    4:'三壘有人',
    5:'一三壘有人',
    6:'二三壘有人',
    7:'滿壘'
}

# 新增一列"球員"，根据"Pitcher"列的值匹配中文名
df_ump['壘包狀態'] = df_ump['壘包狀態編號'].map(name_mapping)

In [69]:
df_ump['PitchofPA'] = df_ump.groupby(['bName', 'pName', 'date', 'gameId', 'paRound', 'paOrder']).cumcount() + 1

In [70]:
# 1. 原始排序邏輯
df_ump.sort_values(by=['date','inning','gameId', 'paRound', 'paOrder','pName', 'bName', 'PitchofPA'], inplace=True)

# 2. 修改後的 get_expected_runs (加入空值檢查)
def get_expected_runs(row):
    base_type = row["壘包狀態編號"]
    outs = row["outs"]
    balls = row["balls"]
    strikes = row["strikes"]
    
    matching_row = RE[(RE["壘包狀態"] == base_type) & 
                      (RE["出局數"] == outs) & 
                      (RE["壞球"] == balls) & 
                      (RE["好球"] == strikes)]
    
    if not matching_row.empty:
        # 確保取出的值不是 None
        val = matching_row.iloc[0]["Expected_Runs"]
        return val if pd.notna(val) else 0
    else:
        return 0 # 找不到對照時回傳 0，避免 None 導致後續崩潰

# 執行計算
df_ump["Expected_Runs"] = df_ump.apply(get_expected_runs, axis=1)

# 3. 執行位移並正確賦值 (避免使用可能失效的 inplace=True)
df_ump["Next_Expected_Runs"] = df_ump.groupby(["date", "gameId", "inning", "side"])["Expected_Runs"].shift(-1)
df_ump["Next_Expected_Runs"] = df_ump["Next_Expected_Runs"].fillna(0)

In [71]:
# 1. 計算該球造成的期望值變動 (Expected Run Value Change)
df_ump['RE_change'] = df_ump['Next_Expected_Runs'] - df_ump['Expected_Runs']

# 2. 定義判別函數
def label_beneficiary(row):
    # 如果判決正確，通常視為公平競爭，但在進階分析中，
    # 若要看「判決結果」對誰有利，不論正確與否，逻辑如下：
    
    # 這裡我們專注於「判決後的結果」：
    # 如果 RE 增加，代表進攻方處境變好 -> 進攻球隊得利
    if row['RE_change'] > 0:
        return row['進攻球隊']
    # 如果 RE 減少，代表進攻方處境變差（好球數增加） -> 防守球隊得利
    elif row['RE_change'] < 0:
        return row['防守球隊']
    else:
        return '無影響'

# 3. 標記受益球隊
df_ump['benefited_team'] = df_ump.apply(label_beneficiary, axis=1)

# 4. 如果只想看「誤判」帶來的得利 (Umpire Error Impact)
def label_missed_call_benefit(row):
    if row['is_correct']:
        return '判決正確'
    
    # 誤判情況下：
    # RE 增加（例如好球誤判為壞球）：進攻方白賺了期望值
    if row['RE_change'] > 0:
        return f"{row['進攻球隊']}"
    # RE 減少（例如壞球誤判為好球）：防守方白賺了期望值
    elif row['RE_change'] < 0:
        return f"{row['防守球隊']}"
    return '誤判-無影響'

df_ump['ump_error_benefit'] = df_ump.apply(label_missed_call_benefit, axis=1)

# 4. 如果只想看「誤判」帶來的得利 (Umpire Error Impact)
def label_missed_call_benefit2(row):
    if row['is_correct']:
        return '判決正確'
    
    # 誤判情況下：
    # RE 增加（例如好球誤判為壞球）：進攻方白賺了期望值
    if row['RE_change'] > 0:
        return '進攻球隊'
    # RE 減少（例如壞球誤判為好球）：防守方白賺了期望值
    elif row['RE_change'] < 0:
        return '防守球隊'
    return '誤判-無影響'

df_ump['ump_error_benefit_team'] = df_ump.apply(label_missed_call_benefit2, axis=1)

df_ump

,LocalDateTime,away,home,id,gameId,stadium,umpireInChief,date,eType,awayScores,...,壘包狀態編號,PitchCount,壘包狀態,PitchofPA,Expected_Runs,Next_Expected_Runs,RE_change,benefited_team,ump_error_benefit,ump_error_benefit_team
15,'2026-05-09T17:13:28.4070+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe096e,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,1,無人在壘,1,0.622645,0.619233,-0.003412,味全,味全,防守球隊
16,'2026-05-09T17:13:44.5340+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe096d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,2,無人在壘,2,0.619233,0.534793,-0.084440,味全,判決正確,判決正確
0,'2026-05-09T17:05:36.0160+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,1,無人在壘,1,0.622645,0.654981,0.032335,味全,判決正確,判決正確
1,'2026-05-09T17:05:51.4260+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097c,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,2,無人在壘,2,0.654981,0.617490,-0.037490,富邦,判決正確,判決正確
3,'2026-05-09T17:06:31.3200+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097a,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,3,無人在壘,3,0.617490,0.551844,-0.065647,富邦,判決正確,判決正確
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,'2026-05-09T20:23:21.7380+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0843,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,7,一壘有人,3,1.020701,0.829502,-0.191199,富邦,判決正確,判決正確
316,'2026-05-09T20:24:04.0870+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0841,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,8,一壘有人,4,0.829502,0.726128,-0.103374,富邦,判決正確,判決正確
319,'2026-05-09T20:26:02.1720+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe083e,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,9,一壘有人,1,0.726128,0.705414,-0.020714,富邦,判決正確,判決正確
320,'2026-05-09T20:26:19.9880+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe083d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,10,一壘有人,2,0.705414,0.655505,-0.049909,富邦,判決正確,判決正確
324,'2026-05-09T20:28:10.3090+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0839,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,11,一壘有人,3,0.655505,0.000000,-0.655505,富邦,判決正確,判決正確

In [72]:
df_ump.info()

<class 'pandas.core.frame.DataFrame'>
Index: 173 entries, 15 to 324
Columns: 287 entries, LocalDateTime to ump_error_benefit_team
dtypes: bool(7), float64(143), int64(17), object(120)
memory usage: 381.0+ KB

In [73]:
#df

In [74]:
df_ump

,LocalDateTime,away,home,id,gameId,stadium,umpireInChief,date,eType,awayScores,...,壘包狀態編號,PitchCount,壘包狀態,PitchofPA,Expected_Runs,Next_Expected_Runs,RE_change,benefited_team,ump_error_benefit,ump_error_benefit_team
15,'2026-05-09T17:13:28.4070+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe096e,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,1,無人在壘,1,0.622645,0.619233,-0.003412,味全,味全,防守球隊
16,'2026-05-09T17:13:44.5340+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe096d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,2,無人在壘,2,0.619233,0.534793,-0.084440,味全,判決正確,判決正確
0,'2026-05-09T17:05:36.0160+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,1,無人在壘,1,0.622645,0.654981,0.032335,味全,判決正確,判決正確
1,'2026-05-09T17:05:51.4260+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097c,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,2,無人在壘,2,0.654981,0.617490,-0.037490,富邦,判決正確,判決正確
3,'2026-05-09T17:06:31.3200+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe097a,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,0,...,0.0,3,無人在壘,3,0.617490,0.551844,-0.065647,富邦,判決正確,判決正確
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,'2026-05-09T20:23:21.7380+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0843,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,7,一壘有人,3,1.020701,0.829502,-0.191199,富邦,判決正確,判決正確
316,'2026-05-09T20:24:04.0870+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0841,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,8,一壘有人,4,0.829502,0.726128,-0.103374,富邦,判決正確,判決正確
319,'2026-05-09T20:26:02.1720+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe083e,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,9,一壘有人,1,0.726128,0.705414,-0.020714,富邦,判決正確,判決正確
320,'2026-05-09T20:26:19.9880+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe083d,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,10,一壘有人,2,0.705414,0.655505,-0.049909,富邦,判決正確,判決正確
324,'2026-05-09T20:28:10.3090+08:00,味全龍 DRAGONS,富邦悍將 GUARDIANS,6a0013ba76ae9f46b0fe0839,6a0013b976ae9f46b0fe0820,新北市立新莊棒球場,江春緯,2026-05-09T09:05:00.000Z,P,8,...,1.0,11,一壘有人,3,0.655505,0.000000,-0.655505,富邦,判決正確,判決正確

# 一致性計算 繪圖

In [75]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from shapely.geometry import Point, Polygon
from scipy.stats import gaussian_kde
from scipy.spatial import ConvexHull

# --- 1. 環境與好球帶設定 ---
STRIKE_ZONE_LEFT, STRIKE_ZONE_RIGHT = -50, 50
STRIKE_ZONE_BOTTOM, STRIKE_ZONE_TOP = -50, 50

TRUE_ZONE_POLY = Polygon([
    (STRIKE_ZONE_LEFT, STRIKE_ZONE_BOTTOM), (STRIKE_ZONE_RIGHT, STRIKE_ZONE_BOTTOM),
    (STRIKE_ZONE_RIGHT, STRIKE_ZONE_TOP), (STRIKE_ZONE_LEFT, STRIKE_ZONE_TOP)
])

plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'Arial Unicode MS', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

# --- 2. 核心計算函數 ---

def build_umpire_zone(df_subset, bandwidth=12, threshold=0.35):
    strikes = df_subset[df_subset["call"] == "S"][["coordX", "coordY"]].dropna().values
    if len(strikes) < 10: return None 
    try:
        kde = gaussian_kde(strikes.T, bw_method=bandwidth / np.std(strikes, axis=0).mean())
        x, y = np.meshgrid(np.linspace(-120, 120, 200), np.linspace(-120, 120, 200))
        z = kde(np.vstack([x.ravel(), y.ravel()])).reshape(200, 200)
        z /= z.max()
        mask_pts = np.column_stack([x[z >= threshold], y[z >= threshold]])
        hull = ConvexHull(mask_pts)
        return Polygon(mask_pts[hull.vertices])
    except: return None

def evaluate_umpire_performance_final(df_subset, true_zone):
    """改用 ump_error_benefit 計算偏袒與獲益球隊"""
    ump_zone = build_umpire_zone(df_subset)
    
    # --- 新增：強制轉換數據型態 ---
    # 將文字轉為 NaN，再將 NaN 填補為 0，確保可以進行運算
    benefit_series = pd.to_numeric(df_subset["ump_error_benefit"], errors='coerce').fillna(0)
    # ---------------------------

    results = []
    for _, row in df_subset.iterrows():
        pt = Point(row["coordX"], row["coordY"])
        in_rule = true_zone.covers(pt)
        in_ump = ump_zone.covers(pt) if ump_zone is not None else False
        
        correct = (in_rule and row["call"] == "S") or (not in_rule and row["call"] == "B")
        consistent = (in_ump and row["call"] == "S") or (not in_ump and row["call"] == "B")
        
        results.append({
            "is_correct": correct,
            "is_consistent": consistent,
            "is_rule_strike": in_rule
        })
    
    eval_df = pd.DataFrame(results)
    total_pitches = len(eval_df)
    
    acc = eval_df["is_correct"].mean()
    con = eval_df["is_consistent"].mean()
    strike_acc = (df_subset[eval_df["is_rule_strike"].values]["call"] == "S").mean()
    ball_acc = (df_subset[~eval_df["is_rule_strike"].values]["call"] == "B").mean()
    
    # --- 修改：使用轉換後的 benefit_series ---
    total_benefit = benefit_series.sum()
    favor_per_100 = (total_benefit / total_pitches) * 100 if total_pitches > 0 else 0
    
    # 判定獲益球隊時，也使用轉換後的數值來運算
    # 這裡建立一個臨時的 Series 來對應球隊
    benefit_df = pd.DataFrame({
        "team": df_subset["benefited_team"],
        "val": benefit_series
    })
    benefit_by_team = benefit_df.groupby("team")["val"].sum()
    
    active_benefits = benefit_by_team.drop(labels=["無影響"], errors="ignore")
    
    if active_benefits.empty or total_benefit == 0:
        f_desc, f_col = "表現中立", "#7f8c8d"
    else:
        # 取得絕對值最大的獲益隊伍
        lucky_team = active_benefits.abs().idxmax()
        f_desc, f_col = f"獲益隊伍：{lucky_team}", "#e67e22" if total_benefit > 0 else "#27ae60"

    return {
        "總球數": total_pitches,
        "整體準確率": round(acc, 4),
        "一致性": round(con, 4),
        "好球準確率": round(strike_acc, 4),
        "壞球準確率": round(ball_acc, 4),
        "總得分偏袒": round(total_benefit, 3),
        "每百球偏袒": round(favor_per_100, 3),
        "偏袒描述": f_desc,
        "偏袒顏色": f_col
    }

# --- 3. 整合繪圖函數 ---

def draw_combined_umpire_card(stats, df_subset, output_path):
    fig, (ax_plot, ax_text) = plt.subplots(1, 2, figsize=(13, 8), gridspec_kw={'width_ratios': [1.2, 1]})
    fig.patch.set_facecolor('#ffffff')

    # 左側：空間分佈
    ax_plot.add_patch(Rectangle((STRIKE_ZONE_LEFT, STRIKE_ZONE_BOTTOM), 100, 100, 
                                linewidth=2, edgecolor='black', facecolor='none', label='Strike Zone', zorder=5))
    
    for _, row in df_subset.iterrows():
        pt = Point(row["coordX"], row["coordY"])
        is_rule_in = TRUE_ZONE_POLY.covers(pt)
        correct = (is_rule_in and row["call"] == "S") or (not is_rule_in and row["call"] == "B")
        if not correct:
            dot_color = '#2ecc71' if row["call"] == "S" else '#e74c3c'
            ax_plot.scatter(row["coordX"], row["coordY"], c=dot_color, s=60, alpha=0.7, edgecolors='k', zorder=7)

    uzone = build_umpire_zone(df_subset)
    if uzone:
        xh, yh = uzone.exterior.xy
        ax_plot.plot(xh, yh, color='#f39c12', linestyle='--', linewidth=3, label='Umpire Zone', zorder=6)

    ax_plot.set_xlim(-140, 140); ax_plot.set_ylim(-140, 140)
    ax_plot.set_aspect('equal'); ax_plot.grid(True, linestyle=':', alpha=0.4)
    ax_plot.legend(loc='lower center', bbox_to_anchor=(0.5, -0.15), ncol=2)
    ax_plot.set_title(f"判決誤判分佈\n({stats['打者對應']})", fontsize=15, fontweight='bold')

    # 右側：數據統計指標
    ax_text.axis('off')
    ax_text.add_patch(Rectangle((0.02, 0.02), 0.96, 0.96, transform=ax_text.transAxes, color='#f8f9fa', zorder=-1))
    
    ax_text.text(0.5, 0.92, f"{stats['年份']} UMPIRE REPORT", fontsize=12, ha='center', color='gray')
    ax_text.text(0.5, 0.86, stats['裁判'], fontsize=28, fontweight='bold', ha='center', color='#2c3e50')
    ax_text.axhline(0.82, 0.1, 0.9, color='#2c3e50', lw=2)

    y_pos = 0.74
    metrics = [
        ("整體準確率", stats['整體準確率'], "#2980b9"),
        ("一致性", stats['一致性'], "#8e44ad"),
        ("好球準確率", stats['好球準確率'], "#27ae60"),
        ("壞球準確率", stats['壞球準確率'], "#e67e22"),
    ]
    for label, val, col in metrics:
        ax_text.text(0.1, y_pos, label, fontsize=14)
        ax_text.text(0.9, y_pos, f"{val:.1%}" if not np.isnan(val) else "N/A", 
                     fontsize=18, fontweight='bold', color=col, ha='right')
        y_pos -= 0.07

    ax_text.axhline(y_pos + 0.03, 0.1, 0.9, color='#dcdde1', ls='--')

    y_pos -= 0.04
    ax_text.text(0.1, y_pos, "總誤判獲益", fontsize=14)
    ax_text.text(0.9, y_pos, f"{stats['總得分偏袒']:+.2f} Runs", fontsize=16, ha='right', color='#34495e')
    
    y_pos -= 0.09
    ax_text.text(0.1, y_pos, "每百球獲益率", fontsize=16, fontweight='bold')
    ax_text.text(0.9, y_pos, f"{stats['每百球偏袒']:+.3f}", 
                 fontsize=24, fontweight='bold', color=stats['偏袒顏色'], ha='right')
    
    y_pos -= 0.05
    ax_text.text(0.9, y_pos, stats['偏袒描述'], fontsize=15, fontweight='bold', color=stats['偏袒顏色'], ha='right')

    ax_text.text(0.5, 0.06, f"總判定球數: {stats['總球數']} 球", ha='center', fontsize=11, color='gray', fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()

# --- 4. 自動化批次處理系統 ---

def generate_umpire_report_system(df_ump):
    base_dir = "Umpire_Game_Analysis_Reports"
    if not os.path.exists(base_dir): os.makedirs(base_dir)

    df_ump = df_ump.dropna(subset=['umpireInChief'])
    
    for (year, umpire), group in df_ump.groupby(['日期', 'umpireInChief']):
        folder_name = f"{year}_{umpire}"
        u_dir = os.path.join(base_dir, folder_name)
        if not os.path.exists(u_dir): os.makedirs(u_dir)
        
        scenarios = [
            ("全部總結", group),
            ("面對左打", group[group['bHand'] == 'L']),
            ("面對右打", group[group['bHand'] == 'R'])
        ]

        for label, sub_df in scenarios:
            if len(sub_df) >= 12: 
                stats = evaluate_umpire_performance_final(sub_df, TRUE_ZONE_POLY)
                stats.update({"年份": year, "裁判": umpire, "打者對應": label})
                
                f_name = f"{year}_{label}.png"
                draw_combined_umpire_card(stats, sub_df, os.path.join(u_dir, f_name))

    print(f"✅ 報表生成完成！請查看資料夾: {base_dir}")

# 執行
generate_umpire_report_system(df_ump)

✅ 報表生成完成！請查看資料夾: Umpire_Game_Analysis_Reports